services:
  frontend:
    container_name: etl-frontend
    build:
      context: .
      args:
        - NEXT_PUBLIC_BUILD_ID=${NEXT_PUBLIC_BUILD_ID:-development}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_KC_URL=${NEXT_PUBLIC_KC_URL}
        - NEXT_PUBLIC_KC_REALM=${NEXT_PUBLIC_KC_REALM}
        - NEXT_PUBLIC_KC_CLIENT_ID=${NEXT_PUBLIC_KC_CLIENT_ID}
    ports:
      - "3000:3000"
    volumes:
      - next_build_cache:/app/.next/cache
    restart: unless-stopped

volumes:
  next_build_cache:
